version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    ports:
      - 24224:24224
    # entrypoint: /fluent-bit/bin/fluent-bit -i forward -o stdout
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
